---
- hosts: workstation

  tasks:
    - name: Install Kaleidoscope
      homebrew_cask: name=kaleidoscope
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Set Kaleidoscope settings
      notify: restart Kaleidoscope
      plist_file:
        dest: com.google.musicmanager
        value:
          BPXLBirthday:
            2.0: 332890
          HockeySDKAutomaticallySendCrashReports: no
          HockeySDKCrashReportActivated: yes
          KS2UpTextScopeViewControllerDefaultsInitialDetailControllerClassNameKey: 0
          KSApplicationFirstLaunch: no
          KSCLIToolsHasUpdatedFromKSDiffFinder: yes
          KSFileSystemItemRepScanHiddenFilesKey: yes
          KSIntegrationWindowControllerFirstLoad: yes
          KSMainWindowControllerFirstLoad: yes
          KSPreferencesWindowControllerFirstLoad: yes
          KSPreferencesWindowControllerPreviousPaneIdentifier: com.blackpixel.preferences.general
          KSTextScopeFontInfoUserDefaultsKey:
            fontName: UbuntuMonoDerivativePowerline-Regular
            fontSize: 15
          KSTextScopeThemeTextStyleTagUserDefaultsKey: 1
          KTSplitView_KSChangesetDocumentViewControllerAutosaveName:
            KTSplitViewAutosaveVersion: 0
            KTSplitViewResizeBehaviour: 1
            KTSplitViewResizeInfo: 280
          NSFontPanelAttributes: 1, 5
          NSQuitAlwaysKeepsWindows: no
          NSToolbar Configuration com.apple.NSColorPanel:
            TB Is Shown: 1
          SUSendProfileInfo: no
          moveToApplicationsFolderAlertSuppress: yes

  handlers:
    - name: restart Kaleidoscope
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - Kaleidoscope
