---
- hosts: workstation

  tasks:
    - name: Install pip
      easy_install: name=pip
      sudo: yes

    - name: Install necessary Python packages
      pip: name={{item}}
      sudo: yes
      with_items:
        - biplist
