---
- name: install
  command: go get {{item.pkg}}
  args:
    creates: /Users/{{user_name}}/.go/bin/{{item.bin}}
  environment:
    GOPATH: /Users/{{user_name}}/.go
  with_items:
    - pkg: golang.org/x/tools/cmd/godex
      bin: godex
    - pkg: golang.org/x/tools/cmd/godoc
      bin: godoc
    - pkg: golang.org/x/tools/cmd/goimports
      bin: goimports
    - pkg: golang.org/x/tools/cmd/gomvpkg
      bin: gomvpkg
    - pkg: golang.org/x/tools/cmd/gorename
      bin: gorename
    - pkg: golang.org/x/tools/cmd/gotype
      bin: gotype
    - pkg: github.com/FiloSottile/gvt
      bin: gvt
    - pkg: github.com/derekparker/delve/cmd/dlv
      bin: dlv
    - pkg: github.com/nsf/gocode
      bin: gocode
    - pkg: github.com/sqs/goreturns
      bin: goreturns
    - pkg: github.com/alecthomas/gometalinter
      bin: gometalinter
    - pkg: github.com/zmb3/gogetdoc
      bin: gogetdoc
    - pkg: github.com/rogpeppe/godef
      bin: godef
    - pkg: golang.org/x/tools/cmd/guru
      bin: guru
