---
- hosts: workstation

  tasks:
    - name: Install Music Manager
      homebrew_cask: name=music-manager
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Set Music Manager settings
      notify: restart Music Manager
      plist_file:
        dest: com.google.musicmanager
        value:
          AccountAutologon: 1
          CommunicationProblems: no
          DownloadAllLastPath: ""
          DownloadAllLocation: 2
          DownloadPurchasedAuto: no
          DownloadPurchasedLastPath: ""
          DownloadPurchasedLocation: 2
          EnableCrashReporting: no
          EnableCrashReporting_Default: no
          EnableUiAutoStart: yes
          EnableUiAutoStart_Default: 1
          FilterOutPodcasts: yes
          ForceLoginResult_Default: -1
          ManualSync: no
          MusicEstimationStatus: 0
          MusicFileUnscannedEstimate: 0
          MusicFilesSharing: 2
          MusicFilesSharing_Default: -1
          MusicFilesUploaded: 0
          MusicFilesWithErrors: 0
          MyMusicFolder:
            - /Users/{{ansible_ssh_user}}/Music
          PlaylistFiltering: 0
          PlaylistsSharing_Default: yes
          PolicyTrackLimit_Default: 2147483647
          RestartPurpose: 0
          RetryOverlimitTracksGeneration: 10
          TraceLevel: INFO
          UserAllowedBandwidthKbps_Default: 2147483647
          UserAllowedDownloadBandwidthKbps_Default: 2147483647
          iTunesLibraryPath: /Users/{{ansible_ssh_user}}/.itunes/iTunes Music Library.xml
          iTunesMusicFolderPath: /Users/{{ansible_ssh_user}}/.itunes/

  handlers:
    - name: restart Music Manager
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - Music Manager
