---
- hosts: workstation

  tasks:
    - name: Install Google Drive
      homebrew_cask: name=google-drive
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Set 1Password settings
      notify: restart Google Drive
      plist_file:
        dest: com.google.GoogleDrive
        value:
          dontwarntrash-folder: yes
          dontwarntrash-gdoc: no
          overlayLogging: no
          overlaysdisabled: no
          thankyoushown: yes
          usagestats: no

  handlers:
    - name: restart Google Drive
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - Google Drive
