---
- hosts: workstation

  tasks:
    - name: Install Bash
      homebrew: name={{item}}
      with_items:
        - bash
        - bash-completion

    - name: Install Zsh
      homebrew: name={{item.name}} install_options={{item.install_options}}
      with_items:
        - name: zsh
          install_options: disable-etcdir

        - name: zsh-syntax-highlighting
          install_options:

        - name: zsh-completions
          install_options:

        - name: zsh
          install_options:

    - name: Install fish
      homebrew: name=fish state=head

    - name: Find out current shell in Directory
      shell: dscl . -read /Users/mtneug UserShell | awk '{print $2}'
      sudo: yes
      register: dscl_user_shell
    - name: Set fish as login shell in Directory
      shell: dscl . -change /Users/{{ansible_ssh_user}} UserShell {{ dscl_user_shell.stdout }} /usr/local/bin/fish
      sudo: yes
    - name: Set fish as login shell in UNIX
      shell: chsh -s /usr/local/bin/fish {{ansible_ssh_user}}
      sudo: yes

    - name: Install other shell CLI tools
      homebrew: name={{item.name}} install_options={{item.install_options}}
      with_items:
        - name: shellcheck
          install_options:

        - name: tmux
          install_options:

        - name: reattach-to-user-namespace
          install_options:

    - name: Install other shell CLI tools (pip)
      pip: name={{item}} state=latest
      with_items:
        - powerline-status

    - name: Install powerline dotfiles
      vcsh:
        name: powerline
        remote: git@github.com:mtneug/dotfiles-powerline.git

    - name: Install other shell CLI tools (gem)
      gem: name={{item}} state=latest user_install=no
      with_items:
        - tmuxinator

    - name: Install tmux dotfiles
      vcsh:
        name: tmux
        remote: git@github.com:mtneug/dotfiles-tmux.git
