---
- hosts: workstation

  tasks:
    - name: Install Burn
      homebrew_cask: name=burn
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Set Burn settings
      notify: restart Burn
      plist_file:
        dest: com.kiwifruitware.Burn
        value:
          DRBurnOptionsBurnSpeed: 65535
          KWAllowMSMPEG4: no
          KWAllowOverBurning: no
          KWBurnOptionsCompletionAction: DRBurnCompletionActionMount
          KWBurnOptionsVerifyBurn: no
          KWCalculateFilePackageSizes: yes
          KWCalculateFolderSizes: yes
          KWCalculateTotalSize: yes
          KWCleanTemporaryFolderAction: 0
          KWCreateAlbumFolders: yes
          KWCreateArtistFolders: yes
          KWCustomDivXSize: no
          KWCustomDivXSoundBitrate: no
          KWCustomDivXVideoBitrate: no
          KWCustomDVDSoundBitrate: no
          KWCustomDVDVideoBitrate: no
          KWCustomFPS: no
          KWDebug: no
          KWDefaultAudioType: 0
          KWDefaultCDMedia: 6
          KWDefaultDataType: 2
          KWDefaultDivXSoundType: 0
          KWDefaultDVDMedia: 4
          KWDefaultDVDSoundType: 0
          KWDefaultMedia: 0
          KWDefaultMP3Bitrate: 129.0
          KWDefaultMP3Mode: 1
          KWDefaultPregap: 1.0
          KWDefaultRegion: 0
          KWDefaultVideoType: 0
          KWDVDForce43: no
          KWDVDTheme: 0
          KWDVDThemeFormat: 0
          KWFirstRun: no
          KWForceDivX: no
          KWForceMPEG2: no
          KWLoopDVD: no
          KWMuxSeperateStreams: no
          KWRememberLastTab: yes
          KWRememberPopups: yes
          KWRemuxMPEG2Streams: no
          KWSaveBorders: no
          KWShowFilePackagesAsFolder: no
          KWShowOverwritableSpace: no
          KWTemporaryLocationPopup: 0
          KWUseCDText: no
          KWUseCustomFFMPEG: no
          KWUseSoundEffects: yes
          KWUseTheme: yes

  handlers:
    - name: restart Burn
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - Burn
