---
- name: install
  homebrew_cask: name=flux

- name: configure
  notify: restart flux
  plist_file:
    dest: org.herf.Flux
    value:
      version: 3
      SUHasLaunchedBefore: true
      firstrun: 1489569110
      location: "51.960665,7.626135"
      locationType: L
      locationTextField: ""
      lateColorTemp: 6500
      nightColorTemp: 3400
      offer-qs: 1
      steptime: 30
      wakeTime: 450
