  .GlobalPreferences:
    AppleHighlightColor: "1.000000 0.937255 0.690196"
    AppleOtherHighlightColor: "1.000000 0.937255 0.690196"
    AppleAquaColorVariant: 6
    AppleAntiAliasingThreshold: 4
    AppleInterfaceStyle: Dark
    # Enable subpixel font rendering on non-Apple LCDs
    AppleFontSmoothing: 2
    AppleLanguages:
      - de
    AppleLocale: "de_DE"
    AppleMeasurementUnits: Centimeters
    AppleMetricUnits: yes
    # disable Double-click a window's title bar to minimize
    AppleMiniaturizeOnDoubleClick: no
    # Finder: show all filename extensions
    AppleShowAllExtensions: yes
    AppleShowScrollBars: WhenScrolling
    AppleSpacesSwitchOnActivate: no
    # Enable full keyboard access for all controls
    # (e.g. enable Tab in modal dialogs)
    AppleKeyboardUIMode: 3
    # 24 hour time
    AppleICUForce12HourTime: no
    AppleICUForce24HourTime: yes
    # Use smooth scrolling
    AppleScrollAnimationEnabled: yes
    # Enable translucent menu bar
    AppleEnableMenuBarTransparency: yes
    # Set scroll direction (new Lion behavior)
    com.apple.swipescrolldirection: yes

    # Sidebar icon size: Small
    NSTableViewDefaultSizeMode: 1

    # Swipe between pages with two fingers
    AppleEnableSwipeNavigateWithScrolls: yes

    # Enable key repeat
    ApplePressAndHoldEnabled: no
    # Set keyboard repeat rate
    KeyRepeat: 1
    # Set a shorter Delay until key repeat
    InitialKeyRepeat: 10

    NSNavPanelFileLastListModeForOpenModeKey: 1
    NSNavPanelFileLastListModeForSaveModeKey: 1
    NavPanelFileListModeForOpenMode: 1
    NSNavPanelFileListModeForOpenMode2: 1
    NavPanelFileListModeForSaveMode: 1
    NSNavPanelFileListModeForSaveMode2: 1

    # Expand save panel by default
    NSNavPanelExpandedStateForSaveMode: yes
    NSNavPanelExpandedStateForOpenMode: yes
    # Expand print panel by default
    PMPrintingExpandedStateForPrint: yes
    PMPrintingExpandedStateForPrint2: yes

    # Save to disk (not to iCloud) by default
    NSDocumentSaveNewDocumentsToCloud: no
    # Display ASCII control characters using caret notation in standard text views
    # Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
    NSTextShowsControlCharacters: yes
    # Disable Resume system-wide
    NSQuitAlwaysKeepsWindows: no
    # Disable automatic termination of inactive apps
    NSDisableAutomaticTermination: yes
    # Enable auto-correct
    NSAutomaticSpellingCorrectionEnabled: yes
    NSAutomaticQuoteSubstitutionEnabled: yes
    NSAutomaticDashSubstitutionEnabled: yes

    # Add a context menu item for showing the Web Inspector in web views
    WebKitDeveloperExtras: yes
    WebAutomaticSpellingCorrectionEnabled: yes

    # Enable spring loading for directories
    com.apple.springing.enabled: yes
    com.apple.springing.delay: "0.5"

    # Animate the focus ring
    NSUseAnimatedFocusRing: yes

    # Ask to keep changes on close
    NSCloseAlwaysConfirmsChanges: 1

    # Disabling App Nap
    NSAppSleepDisabled: "YES"

    # Disable volume change feedback
    com.apple.sound.beep.feedback: 0
