  .GlobalPreferences:
    AppleActionOnDoubleClick: Maximize
    AppleHighlightColor: "1.000000 0.937255 0.690196"
    AppleOtherHighlightColor: "1.000000 0.937255 0.690196"
    AppleAquaColorVariant: 6
    AppleAntiAliasingThreshold: 4
    AppleInterfaceStyle: Dark
    # Enable subpixel font rendering on non-Apple LCDs
    AppleFontSmoothing: 2
    AppleLanguages:
      - de
      - en
    AppleLocale: "de_DE"
    AppleMeasurementUnits: Centimeters
    AppleMetricUnits: yes
    # disable Double-click a window's title bar to minimize
    AppleMiniaturizeOnDoubleClick: no
    # Finder: show all filename extensions
    AppleShowAllExtensions: yes
    AppleShowScrollBars: WhenScrolling
    AppleSpacesSwitchOnActivate: no
    # Enable full keyboard access for all controls
    # (e.g. enable Tab in modal dialogs)
    AppleKeyboardUIMode: 3
    # 24 hour time
    AppleICUForce12HourTime: no
    AppleICUForce24HourTime: yes
    # Use smooth scrolling
    AppleScrollAnimationEnabled: yes
    # Enable translucent menu bar
    AppleEnableMenuBarTransparency: yes
    # Set scroll direction (new Lion behavior)
    com.apple.swipescrolldirection: yes

    # Sidebar icon size: Small
    NSTableViewDefaultSizeMode: 1

    # Swipe between pages with two fingers
    AppleEnableSwipeNavigateWithScrolls: yes

    # Enable key repeat
    ApplePressAndHoldEnabled: no
    # Set keyboard repeat rate
    KeyRepeat: 1
    # Set a shorter Delay until key repeat
    InitialKeyRepeat: 15

    NSNavPanelFileLastListModeForOpenModeKey: 1
    NSNavPanelFileLastListModeForSaveModeKey: 1
    NavPanelFileListModeForOpenMode: 1
    NSNavPanelFileListModeForOpenMode2: 1
    NavPanelFileListModeForSaveMode: 1
    NSNavPanelFileListModeForSaveMode2: 1

    # Expand save panel by default
    NSNavPanelExpandedStateForSaveMode: yes
    NSNavPanelExpandedStateForOpenMode: yes
    # Expand print panel by default
    PMPrintingExpandedStateForPrint: yes
    PMPrintingExpandedStateForPrint2: yes

    # Save to disk (not to iCloud) by default
    NSDocumentSaveNewDocumentsToCloud: no
    # Display ASCII control characters using caret notation in standard text views
    # Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
    NSTextShowsControlCharacters: yes
    # Disable Resume system-wide
    NSQuitAlwaysKeepsWindows: no
    # Disable automatic termination of inactive apps
    NSDisableAutomaticTermination: yes
    # Enable auto-correct
    NSAutomaticSpellingCorrectionEnabled: yes
    NSAutomaticQuoteSubstitutionEnabled: yes
    NSAutomaticDashSubstitutionEnabled: yes

    # Add a context menu item for showing the Web Inspector in web views
    WebKitDeveloperExtras: yes
    WebAutomaticSpellingCorrectionEnabled: yes

    # Enable spring loading for directories
    com.apple.springing.enabled: yes
    com.apple.springing.delay: "0.5"

    # Animate the focus ring
    NSUseAnimatedFocusRing: yes

    # Ask to keep changes on close
    NSCloseAlwaysConfirmsChanges: 1

    # Disabling App Nap
    NSAppSleepDisabled: "YES"

    # Disable volume change feedback
    com.apple.sound.beep.feedback: 0

    # Enable clicking
    com.apple.mouse.tapBehavior: 1

    AKDeviceUnlockState: no
    NSPersonNameDefaultDisplayNameOrder: 2
    NSPersonNameDefaultShortNameFormat: 0
    NSPersonNameDefaultShouldPreferNicknamesPreference: 0
    NSPreferredSpellServerLanguage: de
    NSPreferredSpellServerVendors:
      de: Apple
    NSPreferredWebServices:
      NSWebServicesProviderWebSearch:
        NSDefaultDisplayName: Google
        NSProviderIdentifier: "com.google.www"
    NSSpellCheckerAutomaticallyIdentifiesLanguages: yes
    _HIHideMenuBar: no
    com.apple.DictionaryServices:
      DCSActiveDictionaries:
        - "/Library/Dictionaries/German - English.dictionary"
        - "/Library/Dictionaries/Duden Dictionary Data Set I.dictionary"
        - "/Library/Dictionaries/Apple Dictionary.dictionary"
        - "/System/Library/Frameworks/CoreServices.framework/Frameworks/DictionaryServices.framework/Resources/Wikipedia.wikipediadictionary"
        - "/Library/Dictionaries/Oxford Thesaurus of English.dictionary"
        - "/Library/Dictionaries/Oxford Dictionary of English.dictionary"
      DCSDictionaryPrefs:
        com.apple.dictionary.Wikipedia:
          language-ar: 0
          language-ca: 0
          language-cs: 0
          language-da: 0
          language-de: 1
          language-el: 0
          language-en: 1
          language-es: 0
          language-fi: 0
          language-fr: 0
          language-he: 0
          language-hr: 0
          language-hu: 0
          language-it: 0
          language-ja: 0
          language-ko: 0
          language-nl: 0
          language-no: 0
          language-pl: 0
          language-pt: 0
          language-ro: 0
          language-ru: 0
          language-sk: 0
          language-sv: 0
          language-th: 0
          language-tr: 0
          language-uk: 0
          language-zh/cn/hans: 0
          language-zh/tw/hant: 0
    userMenuExtraStyle: 2
