  com.apple.driver.AppleHIDMouse:
    Button1: yes
    Button2: yes
    Button3: no
    Button4: no
    Button4Click: 0
    Button4Force: 0
    ButtonDominance: 1
    ScrollH: 1
    ScrollS: 4
    ScrollSSize: 30
    ScrollV: 1
