  com.apple.sidebarlists:
    favoriteservers:
      Controller: CustomListItems
      CustomListItems:
        - Name: "http://ipad-mt.intern"
          URL: "http://ipad-mt.intern"
        - Name: "afp://homeserver.intern"
          URL: "afp://homeserver.intern"
        - Name: "afp://homeserver.intern:549"
          URL: "afp://homeserver.intern:549"
    networkbrowser:
      CustomListProperties:
        com.apple.NetworkBrowser.bonjourEnabled: yes
    systemitems:
        Controller: VolumesList
        ShowEjectables: yes
        ShowHardDisks: yes
        ShowRemovable: yes
        ShowServers: yes
