  com.apple.addressbook:
    # Enable the debug menu in Address Book
    ABShowDebugMenu: yes

    # Address format
    ABDefaultAddressCountryCode: de

    # Display format "Last, First"
    ABNameDisplay: 1

    # Sort by last name
    ABNameSortingFormat: sortingLastName sortingFirstName
