  com.apple.DiskUtility:
    DRBurnOptionsBurnSpeed: 65535
    DRBurnOptionsCompletionAction: DRBurnCompletionActionEject
    DRBurnOptionsVerifyBurn: yes
    DRBurnSetupPanelExpanded: yes
    DUShowDetailsInFirstAid: yes

    # Enable the debug menu in Disk Utility
    DUDebugMenuEnabled: 1
    advanced-image-options: yes
