  com.apple.Spotlight:
    WebKitCacheModelPreferenceKey: 1
    __NSEnableTSMDocumentWindowLevel: yes

    # Disable disclaimer text in Yosemite
    useCount: 3
    showedFTE: yes

    orderedItems:
      - enabled: yes
        name: APPLICATIONS
      - enabled: yes
        name: MENU_SPOTLIGHT_SUGGESTIONS
      - enabled: yes
        name: MENU_CONVERSION
      - enabled: yes
        name: MENU_EXPRESSION
      - enabled: yes
        name: MENU_DEFINITION
      - enabled: yes
        name: SYSTEM_PREFS
      - enabled: yes
        name: DOCUMENTS
      - enabled: yes
        name: DIRECTORIES
      - enabled: yes
        name: PRESENTATIONS
      - enabled: yes
        name: SPREADSHEETS
      - enabled: yes
        name: PDF
        # Messages will display images in mails
      - enabled: no
        name: MESSAGES
      - enabled: yes
        name: CONTACT
      - enabled: yes
        name: EVENT_TODO
      - enabled: yes
        name: IMAGES
      - enabled: yes
        name: BOOKMARKS
      - enabled: yes
        name: MUSIC
      - enabled: yes
        name: MOVIES
      - enabled: yes
        name: FONTS
      - enabled: yes
        name: MENU_OTHER
      - enabled: yes
        name: MENU_WEBSEARCH
      - enabled: yes
        name: SOURCE
