  com.apple.driver.AppleBluetoothMultitouch.mouse:
    UserPreferences: yes

    MouseButtonDivision: 55
    # Secondary click:
    # Possible values: OneButton, TwoButton, TwoButtonSwapped
    MouseButtonMode: OneButton

    MouseHorizontalScroll: yes
    MouseMomentumScroll: yes
    MouseVerticalScroll: yes

    # Smart zoom enabled, double-tap with one finger (set to 0 to disable)
    MouseOneFingerDoubleTapGesture: 0
    # Double-tap with two fingers to Mission Control (set to 0 to disable)
    MouseTwoFingerDoubleTapGesture: 3
    # Two finger horizontal swipe
    # 0 = Swipe between pages with one finger
    # 1 = Swipe between pages
    # 2 = Swipe between full screen apps with two fingers, swipe between pages with one finger (Default Mode)
    MouseTwoFingerHorizSwipeGesture: 2
