  com.apple.ibtool:
    IBAppliesAutoResizingRulesWhileResizing: no
    IBPreserveBundleContentsDuringSaves: yes

    WebKitMinimumFontSize: 1
    WebKitDefaultFixedFontSize: 12
    WebKitDefaultFontSize: 12

    WebKitPluginsEnabled: no
    WebKitJavaEnabled: no
    WebKitJavaScriptCanOpenWindowsAutomatically: no
