  com.apple.HIToolbox:
    AppleCurrentKeyboardLayoutInputSourceID: "com.apple.keylayout.German"
    AppleDictationAutoEnable: yes

    AppleEnabledInputSources:     
      - InputSourceKind: Keyboard Layout
        KeyboardLayout ID: 3
        KeyboardLayout Name: German

    AppleSavedCurrentInputSource:     
      - InputSourceKind: Keyboard Layout
        KeyboardLayout ID: 3
        KeyboardLayout Name: German

    AppleSelectedInputSources:     
      - InputSourceKind: Keyboard Layout
        KeyboardLayout ID: 3
        KeyboardLayout Name: German

    AppleDateResID:
      smRoman: 3

    AppleNumberResID:
      smRoman: 3

    AppleTimeResID:
      smRoman: 3
