  com.apple.loginwindow:
    # disable reopen windows at login
    TALLogoutSavesState: no
    LoginwindowLaunchesRelaunchApps: no

    # Hooks
    # LogoutHook: /path/to/script
    # LoginHook: /path/to/script

    # Old power button behavior
    PowerButtonSleepsSystem: no