  com.apple.speech.recognition.AppleSpeechRecognition.prefs:
    DictationIMIntroMessagePresented: yes
    DictationIMPresentedOfflineUpgradeSuggestion: yes

    DictationIMMasterDictationEnabled: no
    DictationIMUseOnlyOfflineDictation: no
