  com.apple.messageshelper.MessageController:
    SOInputLineSettings:
      # Enable automatic emoji substitution (i.e. use plain text smileys)
      automaticEmojiSubstitutionEnablediMessage: yes

      # Disable smart quotes as it’s annoying for messages that contain code
      automaticQuoteSubstitutionEnabled: no

      # Enable continuous spell checking
      continuousSpellCheckingEnabled: yes
