  com.apple.digihub:
    # Disable all auto actions
    com.apple.digihub.blank.bd.appeared:
      action: 1

    com.apple.digihub.blank.cd.appeared:
      action: 1

    com.apple.digihub.blank.dvd.appeared:
      action: 1

    com.apple.digihub.cd.music.appeared:
      action: 1

    com.apple.digihub.dvcamera.IIDC.appeared:
      action: 1

    com.apple.digihub.dvcamera.IIDC.irisopened:
      action: 1

    com.apple.digihub.dvd.video.appeared:
      action: 1

    com.apple.digihub.dvddvcamera.appeared:
      action: 1
