  com.apple.iCal:
    CalDefaultCalendar: UseLastSelectedAsDefaultCalendar
    CalDefaultCalendarSelectedByUser: no
    CalUICanvasOccurrenceFontSize: 12
    CalendarListMiniMonthVisibleMonths: 1
    CalendarSidebarWidth: 168

    DisableEmphasizedViews: yes

    lastViewsTimeZone: Europe/Berlin
    PersistentMenu-lastUsedTimeZones:
      - name: Europe/Berlin

    CalendarSidebarShown: yes
    TimeZone support enabled: no
    # Show week numbers (10.8 only)
    Show Week Numbers: yes
    # Show 7 days
    n days of week: 7
    # Show event times
    Show time in Month View: yes

    first day of week: 0
    first minute of day time range: 0
    first shown minute of day": 624.6760563380282
    last calendar view description: "7-day"
    last minute of day time range: 1440


