  com.apple.driver.AppleBluetoothMultitouch.trackpad:
    UserPreferences: yes

    USBMouseStopsTrackpad: no

    # Tap to click
    Clicking: yes
    DragLock: no
    Dragging: no

    TrackpadCornerSecondaryClick: no
    TrackpadHandResting: yes
    TrackpadMomentumScroll: yes
    # Zoom in or out
    TrackpadPinch: yes
    # Tap with two fingers to emulate right click
    TrackpadRightClick: yes
    # Enable rotate
    TrackpadRotate: yes
    TrackpadHorizScroll: yes
    TrackpadScroll: yes

    # Smart zoom, double-tap with two fingers
    TrackpadTwoFingerDoubleTapGesture: yes
    # Notification Center
    TrackpadTwoFingerFromRightEdgeSwipeGesture: 3

    # Disable three finger drag
    TrackpadThreeFingerDrag: no
    # Swipe between full-screen apps
    TrackpadThreeFingerHorizSwipeGesture: 2
    TrackpadThreeFingerTapGesture: 0
    TrackpadThreeFingerVertSwipeGesture: 0

    TrackpadFourFingerHorizSwipeGesture: 2
    TrackpadFourFingerPinchGesture: 2
    TrackpadFourFingerVertSwipeGesture: 2

    TrackpadFiveFingerPinchGesture: 2
