  com.apple.Console:
    Bounce: no

    LogOutlineViewVisible: yes
    LogOutlineViewWidth: 341

    MessageInspectorVisible: yes
    MessagesDisplayStyle: 15

    TagsSidebarCollapsed: 1
    WrapLines: 1

    "NSToolbar Configuration LogWindowToolbar":
      "TB Display Mode": 1
      "TB Icon Size Mode": 1
      "TB Is Shown": 1
      "TB Size Mode": 1

    "NSToolbar Configuration com.apple.NSColorPanel":
      "TB Is Shown": 1
