---
- hosts: workstation

  tasks:
    - name: Install Skim
      homebrew_cask: name=skim
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Set Skim settings
      notify: restart Skim
      plist_file:
        dest: net.sourceforge.skim-app.skim
        value:
          NSToolbar Configuration SKDocumentToolbar:
            TB Display Mode: 1
            TB Icon Size Mode: 1
            TB Is Shown: 0
            TB Size Mode: 1
          NSToolbar Configuration com.apple.NSColorPanel:
            TB Is Shown: 1
          SKAutoCheckFileUpdate: yes
          SKLastSelectedPreferencePane: SyncPreferences
          SKLastToolMode: 2
          SKLastVersionLaunched: 88
          SKLeftSidePaneWidth: 0
          SKRememberLastPageViewed: yes
          SKRightSidePaneWidth: 0
          SKShowStatusBar: no
          SKReopenLastOpenFiles: no
          SKTeXEditorArguments: '"%file":%line'
          SKTeXEditorCommand: atom
          SKTeXEditorPreset: Atom
          SUEnableAutomaticChecks: yes
          SUSendProfileInfo: no

  handlers:
    - name: restart Skim
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - Skim
