---

- name: Set Mac OS X System settings
  when: osx_config[item] is defined
  plist_file:
    dest:  "{{ item }}"
    value: "{{ osx_config[item] }}"
  notify: restart after configuration
  register: osx_config_results
  with_items:
    - .GlobalPreferences
    - com.apple.ActivityMonitor
    - com.apple.addressbook
    - com.apple.AppleMultitouchTrackpad
    - com.apple.appleseed.FeedbackAssistant
    - com.apple.appstore
    - com.apple.archiveutility
    - com.apple.assistant.support
    - com.apple.assistant
    - com.apple.BezelServices
    - com.apple.BluetoothAudioAgent
    - com.apple.Console
    - com.apple.CoreGraphics
    - com.apple.CrashReporter
    - com.apple.dashboard
    - com.apple.desktopservices
    - com.apple.digihub
    - com.apple.DiskUtility
    - com.apple.dock
    - com.apple.driver.AppleBluetoothMultitouch.mouse
    - com.apple.driver.AppleBluetoothMultitouch.trackpad
    - com.apple.driver.AppleHIDMouse
    - com.apple.dt.Xcode
    - com.apple.finder
    - com.apple.frameworks.diskimages
    - com.apple.helpviewer
    - com.apple.HIToolbox
    - com.apple.iApps
    - com.apple.ibtool
    - com.apple.iCal
    - com.apple.icbaccountsd
    - com.apple.icloud.fmfd
    - com.apple.identityservicesd
    - com.apple.LaunchServices
    - com.apple.loginitems
    - com.apple.loginwindow
    - com.apple.mail
    - com.apple.menuextra.battery
    - com.apple.menuextra.clock
    - com.apple.messageshelper.MessageController
    - com.apple.NetworkBrowser
    - com.apple.print.PrintingPrefs
    - com.apple.ProblemReporter
    - com.apple.quicklook.satellite
    - com.apple.quicklookconfig
    - com.apple.Safari
    - com.apple.screencapture
    - com.apple.screensaver
    - com.apple.security.cloudkeychainproxy3.keysToRegister
    - com.apple.SetupAssistant
    - com.apple.sharingd
    - com.apple.sidebarlists
    - com.apple.SoftwareUpdate
    - com.apple.spaces
    - com.apple.speech.recognition.AppleSpeechRecognition.prefs
    - com.apple.speech.synthesis.general.prefs
    - com.apple.speech.voice.prefs
    - com.apple.Spotlight
    - com.apple.symbolichotkeys
    - com.apple.syncserver
    - com.apple.systempreferences
    - com.apple.systemsound
    - com.apple.systemuiserver
    - com.apple.TelephonyUtilities
    - com.apple.Terminal
    - com.apple.TextEdit
    - com.apple.TimeMachine
    - com.apple.universalaccess
    - com.apple.universalaccessAuthWarning
    - com.apple.UserAccountUpdater
    - org.x.X11
