---
- hosts: workstation

  tasks:
    - name: Install Skype
      homebrew_cask: name=skype
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Set Skype settings
      notify: restart Skype
      plist_file:
        dest: com.skype.skype
        value:
          AutoCollapseChatView: yes
          AutoCollapseSidebar: no
          DialpadOpen: yes
          DisableWebKitDeveloperExtras: no
          DiscloseConversationParticipants: yes
          HockeySDKAutomaticallySendCrashReports: no
          HockeySDKCrashReportActivated: no
          IncludeDebugMenu: yes
          LastUserSidebarWidth: 124
          SKChatInputAutomaticDashSubstitution: no
          SKChatInputAutomaticQuoteSubstitution: no
          SKChatInputAutomaticSpellingCorrection: no
          SKChatInputContinuousSpellChecking: yes
          SKDisableWelcomeTour: yes
          SKRememberPassword: yes
          SKScreensharingFullScreenDisplayIndex: yes
          SKShowSilentUpgradeNotice: no
          SKShowWelcomeTour: no
          SKUserContactListColumnSizesPreferences:
            favorite: 30
            location: 137
            name: 200
            status: 200
            tags: 150
          ShowDialpadOnLogin: no
          ShowVideoCollapsedInCallsMonitor: no
          SkypeAlertPrefsSelectedTabViewIdentifier: overview
          WebKitDeveloperExtras: yes

  handlers:
    - name: restart Skype
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - Skype
