---
- hosts: workstation

  tasks:
    - name: Create 1Password settings directory
      file:
        path: "{{item}}"
        state: directory
        mode: 0700
      with_items:
        - /Users/{{ansible_ssh_user}}/Library/Containers/com.agilebits.onepassword-osx/Data/Library/Preferences
        - /Users/{{ansible_ssh_user}}/Library/Containers/2BUA8C4S2C.com.agilebits.onepassword-osx-helper/Data/Library/Preferences

    - name: Set 1Password settings
      notify: restart 1Password
      plist_file:
        dest: /Users/{{ansible_ssh_user}}/Library/Containers/com.agilebits.onepassword-osx/Data/Library/Preferences/com.agilebits.onepassword-osx.plist
        value:
          CompletedEssentialSettings: yes
          HockeySDKAutomaticallySendCrashReports: no
          HockeySDKCrashReportActivated: yes
          KeepHelperRunning: yes
          LockOnIdle: yes
          LockOnMainAppExit: no
          PasswordAvoidAmbiguous: no
          PasswordDigits: 7
          PasswordLength: 30
          PasswordSymbols: 7
          ShowRichIcons: yes
          ShowStatusItem: yes
          WelcomeWindowShown: yes

    - name: Set 1Password helper settings
      notify: restart 1Password
      plist_file:
        dest: /Users/{{ansible_ssh_user}}/Library/Containers/2BUA8C4S2C.com.agilebits.onepassword-osx-helper/Data/Library/Preferences/2BUA8C4S2C.com.agilebits.onepassword-osx-helper.plist
        value:
          CheckForSoftwareUpdatesEnabled: yes
          CheckForSoftwareUpdatesIncludeBetas: no
          ClearPasteboardAfterTimeout: yes
          ConcealPasswords: yes
          HashSectionIsSortedFirst: no
          HockeySDKAutomaticallySendCrashReports: no
          HockeySDKCrashReportActivated: yes
          LockOnIdle: yes
          LockOnScreenSaver: yes
          LockOnSleep: yes
          LockOnUserSwitch: yes
          LockTimeout: 5
          OPUserMetricsLaunchCountKey: 15
          PasswordDigits: 10
          PasswordLength: 25
          PasswordRecipeVisible: yes
          PasswordSymbols: 6
          PasteboardClearTimeout: 90
          ShortcutRecorder BrowserActivation:
            keyChars: \
            keyCharsIgnoringModifiers: \
            keyCode: 42
            modifierFlags: 1048576
            modifiers: 256
          ShortcutRecorder GlobalActivation:
            keyChars: \
            keyCharsIgnoringModifiers: \
            keyCode: 42
            modifierFlags: 1572864
            modifiers: 2304
          ShortcutRecorder GlobalLock:
            keyChars: ""
            keyCharsIgnoringModifiers: l
            keyCode: 37
            modifierFlags: 1835008
            modifiers: 6400
          ShowBackupCompletedNotifications: yes
          ShowRichIcons: yes
          ShowStatusItem: yes
          SystemIdleTimeIsBroken: Y
          install-jse-already-shown-com.apple.Safari: yes
          install-jse-already-shown-com.google.Chrome: yes
          install-jse-already-shown-org.mozilla.firefox: yes

    - name: Change rights
      file:
        path: "{{item}}"
        mode: 0600
      with_items:
        - /Users/{{ansible_ssh_user}}/Library/Containers/com.agilebits.onepassword-osx/Data/Library/Preferences/com.agilebits.onepassword-osx.plist
        - /Users/{{ansible_ssh_user}}/Library/Containers/2BUA8C4S2C.com.agilebits.onepassword-osx-helper/Data/Library/Preferences/2BUA8C4S2C.com.agilebits.onepassword-osx-helper.plist

  handlers:
    - name: restart 1Password
      shell: killall {{item}}
      ignore_errors: yes
      with_items:
        - 1Password
        - 1Password mini
