---
- hosts: workstation

  tasks:
    - name: Install Atom
      homebrew_cask: name=atom
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"

    - name: Install Atom packages
      apm: name={{item}}
      with_items:
        - atom-material-ui

        - base16-syntax
        - atom-material-syntax
        - pen-paper-coffee-syntax
        - filter-syntax


        - api-blueprint-preview
        - atom-alignment
        - atom-beautify
        - auto-copyright
        - auto-update-packages
        - autoclose-html
        - autohide-tree-view
        - bezier-curve-editor
        - block-travel
        - capybara-snippets
        - change-case
        - color-picker
        - column-select
        - compass
        - coverage
        - cucumber
        - dash
        - devdocs
        - docblockr
        - editorconfig
        - emmet
        - file-icons
        - filesize
        - gitignore-snippets
        - go-plus
        - go-rename
        - highlight-line
        - highlight-selected
        - ide-flow
        - incremental-search
        - ios
        - javascript-snippets
        - merge-conflicts
        - minimap
        - minimap-find-and-replace
        - minimap-git-diff
        - minimap-highlight-selected
        - minimap-pigments
        - minimap-selection
        - pane-layout-plus
        - pdf-view
        - pigments
        - pulsing-cursor
        - rails-transporter
        - rspec-snippets
        - ruby-test
        - show-in-system
        - skim-displayline
        - sourcegraph-atom
        - stacktrace
        - tabulation-control
        - temporary-root
        - term2
        - tidy-markdown
        - todo-show
        - toggle-quotes
        - trailing-spaces
        - transform
        - vim-mode


        - autocomplete-emojis
        - autocomplete-paths
        - autocomplete-ruby
        - autocomplete-python
        - autocomplete-sass


        - language-apache
        - language-api-blueprint
        - language-asciidoc
        - language-d
        - language-danger
        - language-docker
        - language-diff
        - language-generic-config
        - language-gitignore
        - language-gradle
        - language-groovy
        - language-haml
        - language-handlebars
        - language-ini
        - language-latex
        - language-lisp
        - language-nginx
        - language-proguard
        - language-puppet
        - language-r
        - language-restructuredtext
        - language-rspec
        - language-scala
        - language-slim
        - language-svg
        - language-swift
        - language-viml


        - linter
        - linter-clang
        - linter-coffeelint
        - linter-cpplint
        - linter-csslint
        - linter-erb
        - linter-eslint
        - linter-flow
        - linter-golinter
        - linter-gotype
        - linter-govet
        - linter-htmlhint
        - linter-javac
        - linter-js-yaml
        - linter-jscs
        - linter-jshint
        - linter-perl
        - linter-php
        - linter-rubocop
        - linter-ruby
        - linter-scalac
        - linter-scss-lint
        - linter-shellcheck
        - linter-slim
        - linter-write-good
        - linter-xmllint

    - name: Install atom dotfiles
      vcsh:
        name: atom
        remote: git@github.com:mtneug/dotfiles-atom.git
