---
- name: install
  homebrew_cask: name=atom

- name: install packages
  apm: name={{item}}
  with_items:
    # TODO: select relevant packages

    # UI
    # - atom-material-ui
    - nord-atom-ui
    # - nucleus-dark-ui

    # Syntax theme
    # - duotone-dark-earth-syntax
    # - duotone-dark-space-syntax
    # - earthsung-by-jackson-syntax
    # - filter-syntax
    # - gruvbox
    - nord-atom-syntax
    # - pen-paper-coffee-syntax
    # - redui-jm-syntax
    # - vector-syntax

    # Other design elements
    - file-icons

    # Languages
    - language-apache
    - language-asciidoc
    - language-danger
    - language-diff
    - language-docker
    - language-fish-shell
    - language-generic-config
    - language-gitignore
    - language-gradle
    - language-groovy
    - language-ini
    - language-latex
    - language-lisp
    - language-lua
    - language-nginx
    - language-protobuf
    - language-r
    - language-rspec
    - language-scala
    - language-svg
    - language-swift
    - language-viml

    # Linter
    - linter
    # - linter-clang
    # - linter-cpplint
    # - linter-csslint
    # - linter-eslint
    # - linter-flake8
    # - linter-htmlhint
    # - linter-javac
    - linter-js-yaml
    # - linter-jscs
    - linter-jshint
    # - linter-lintr
    # - linter-pylint
    # - linter-rubocop
    - linter-ruby
    # - linter-scalac
    # - linter-scss-lint
    - linter-shellcheck
    - linter-spell
    - linter-spell-html
    - linter-spell-latex
    - linter-write-good
    # - linter-xmllint
    # - gometalinter-linter

    # Builder
    - build
    - build-make

    # Autocompleter
    # - autocomplete-emojis
    - autocomplete-look
    - autocomplete-paths
    - autocomplete-python

    # Minimap
    - minimap
    # - minimap-find-and-replace
    # - minimap-git-diff
    # - minimap-highlight-selected
    # - minimap-pigments
    # - minimap-selection

    # Text-clicking UI
    # - hyperclick
    # - go-hyperclick

    # Snippets
    - gitignore-snippets

    # Go
    # - builder-go
    # - go-config
    # - go-debug
    # - go-get
    # - gofmt
    # - gorename

    # Web
    - autoclose-html
    - bezier-curve-editor
    - color-picker

    # Markup language
    # - markdown-pdf
    # - markdown-preview-plus

    # Atom Editor
    - atom-alignment
    - atom-beautify
    - block-travel
    # - docblockr
    # - editorconfig
    - highlight-selected
    - pulsing-cursor
    - pigments
    - trailing-spaces
    - transform
    # - vim-mode

    # Atom Statusbar
    - busy
    - filesize
    - tabulation-control

    # Atom
    - autoupdate-packages
    - term3
    - todo-show
