---
- name: add taps
  notify: update homebrew
  homebrew_tap:
    name:
      - homebrew/dupes
      - homebrew/science
      - caskroom/versions
      - caskroom/fonts
      - neovim/neovim

- meta: flush_handlers
