---
- name: install
  homebrew: name=node install_options=with-openssl

- name: install global npm packages
  npm: name={{item}} global=yes
  with_items:
    - bower
    - grunt-cli
    - gulp-cli
    - node-inspector
    - yo
