---
- name: install
  homebrew:
    name: git
    install_options:
      - with-gettext
      - with-brewed-curl
      - with-brewed-openssl

- name: configure
  vcsh: name=dotfiles-git remote=git@github.com:mtneug/dotfiles-git.git
