---
- name: install
  homebrew: name={{item}}
  with_items:
    - yarn

- name: install (npm)
  npm: name={{item}} global=yes
  with_items:
    - bower
    - grunt-cli
    - gulp-cli
    - node-inspector
    - yo
